### PR TITLE
for fixing the issue where subgroup is not used properly for diff map…

### PR DESCRIPTION
**Pull request by dkong-bmgf**
… calculation

### CODE REVIEW

**Comment by emilydriano** [comment]
When I first open the UI, I see the following errors but seems to work fine when I click the 'x' in the top right. Looks like a linting issue? 
image

**Comment by emilydriano** [comment]
also could you clarify what the original issue was here? I want to make sure I'm doing the correct steps to make sure the issue is resolved.

**Comment by dkong-bmgf** [comment]
Could it be your IDE settings that it is set to use "CRLF"?  If you are using VS code, take a look at the bottom right corner to see the settings.  
image

**Comment by dkong-bmgf** [comment]
this is for fixing the calculation on the map when users  hover on a region.  In the example below, the percentage for Saint-louis using modern method ( for all women) is 21.86%.  The percentage for Model method (Women 15-24, Rural) is 13.82.  

When diff map is "On", the percentage should be 13.82% - 21.86% =  -8.58%.


image

**Review by emilydriano — APPROVED** [review]

**Pull request merged**
